<a href="https://colab.research.google.com/github/AndreHidayatullah/DAA/blob/main/DAA_Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [27]:
from datetime import date
tgl_v1 = date.today()
print(tgl_v1)

import datetime as vDate
tanggal = vDate.date.today()
print(tanggal)

mahasiswa = ["Ranti", "2024072001","Informatika", "DAA", f"{tanggal.day}-{tanggal.month}-{tanggal.year}", "Universitas Pembangunan Jaya"]
print (mahasiswa)

2025-09-19
2025-09-19
['Ranti', '2024072001', 'Informatika', 'DAA', '19-9-2025', 'Universitas Pembangunan Jaya']


In [28]:
print("NIM", mahasiswa[1])
print("Kampus", mahasiswa[5])

NIM 2024072001
Kampus Universitas Pembangunan Jaya


In [29]:
#nim saja
print("NIM", mahasiswa[1:2])

NIM ['2024072001']


In [30]:
#prodi saja
print("prodi", mahasiswa[2:3])

prodi ['Informatika']


In [31]:
#nim dan prodi
print("NIM & Prodi", mahasiswa[1:3])

NIM & Prodi ['2024072001', 'Informatika']


In [32]:
#MK dan tanggal
print("Mata Kuliah tanggal berapa?", mahasiswa[3:5])

Mata Kuliah tanggal berapa? ['DAA', '19-9-2025']


In [33]:
#tampilan nama kampus saja menggunakan slicing
print("nama kampus", mahasiswa[5:6])

nama kampus ['Universitas Pembangunan Jaya']


In [34]:
mahasiswa = ["Ranti", "2024072001", "Prodi Informatika", "DAA", str(tanggal), "Universitas Pembangunan Jaya"]
print(mahasiswa)

['Ranti', '2024072001', 'Prodi Informatika', 'DAA', '2025-09-19', 'Universitas Pembangunan Jaya']


In [35]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in  bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [38]:
for aMhs in mahasiswa:
    print(aMhs + ' UPJ')

Ranti UPJ
2024072001 UPJ
Prodi Informatika UPJ
DAA UPJ
2025-09-19 UPJ
Universitas Pembangunan Jaya UPJ


In [37]:
for aMhs in mahasiswa:
    print("UPJ " + aMhs)

UPJ Ranti
UPJ 2024072001
UPJ Prodi Informatika
UPJ DAA
UPJ 2025-09-19
UPJ Universitas Pembangunan Jaya


In [39]:
bin_colors = ('Red', 'Green', 'Blue', 'Yellow')
bin_colors[1]

'Green'

In [40]:
bin_colors[2:]

('Blue', 'Yellow')

In [41]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ)


('Universitas', 'Pembangunan', 'Jaya')


In [42]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))
print(nested_tuple)


(100, (200, 400, 600), 300, (400, 800))


In [43]:
print(nested_tuple[1][2])

600


In [45]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [46]:
bin_colors.get('approved_color')

'Green'

In [47]:
bin_colors['approved_color']

'Green'

In [48]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [50]:
data_mahasiswa = {
    "Nama": "Andre Hidayatullah Putra",
    "NIM": "2024071009",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(data_mahasiswa)


{'Nama': 'Andre Hidayatullah Putra', 'NIM': '2024071009', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [53]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [55]:
green = {'grass', 'leaves', 'leaves'}
print(green)

{'leaves', 'grass'}


In [58]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [59]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [61]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [62]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [63]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [64]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [65]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [66]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [67]:
myVector = [22, 33, 44, 55]
print(myVector)

[22, 33, 44, 55]


In [68]:
print(type(myVector))

<class 'list'>


In [69]:
myVector = np.array([22, 33, 44, 55])
print(myVector)

[22 33 44 55]


In [70]:
print(type(myVector))

<class 'numpy.ndarray'>


In [75]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        else:
            return None

    def is_empty(self):
        return len(self.items) == 0

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        else:
            return None

    def size(self):
        return len(self.items)

In [79]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [80]:
stack.pop()

'Yellow'

In [83]:
stack.is_empty()

False

In [85]:
class Queue(object):
  def __init__(self):
    self.item = []
  def isEmpty(self):
    return self.item==[]
  def enque(self,item):
    self.item.insert(0,item)
  def deque(self):
    return self.item.pop()
  def size(self):
    return len(self.item)

In [87]:
queue = Queue()
queue.enque('Red')
queue.enque('Green')
queue.enque('Blue')
queue.enque('Yellow')
print(queue.size())

4


In [90]:
print(queue.deque())

Red


In [91]:
print(queue.deque())

Green
